=begin
#Klaviyo API (Beta)

#The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

The version of the OpenAPI document: 2022-11-14.pre
Contact: developers@klaviyo.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KlaviyoBetaAPI::OnsiteSubscriptionCreateQueryAsSubResourceAttributes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KlaviyoBetaAPI::OnsiteSubscriptionCreateQueryAsSubResourceAttributes do
  let(:instance) { KlaviyoBetaAPI::OnsiteSubscriptionCreateQueryAsSubResourceAttributes.new }

  describe 'test an instance of OnsiteSubscriptionCreateQueryAsSubResourceAttributes' do
    it 'should create an instance of OnsiteSubscriptionCreateQueryAsSubResourceAttributes' do
      expect(instance).to be_instance_of(KlaviyoBetaAPI::OnsiteSubscriptionCreateQueryAsSubResourceAttributes)
    end
  end
  describe 'test attribute "list_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "custom_source"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "email"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "phone_number"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "properties"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
