=begin
#Klaviyo API (Beta)

#The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

The version of the OpenAPI document: 2022-11-14.pre
Contact: developers@klaviyo.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KlaviyoBetaAPI::TagGroupCreateQuery
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KlaviyoBetaAPI::TagGroupCreateQuery do
  let(:instance) { KlaviyoBetaAPI::TagGroupCreateQuery.new }

  describe 'test an instance of TagGroupCreateQuery' do
    it 'should create an instance of TagGroupCreateQuery' do
      expect(instance).to be_instance_of(KlaviyoBetaAPI::TagGroupCreateQuery)
    end
  end
  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
