=begin
#Klaviyo API (Beta)

#The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

The version of the OpenAPI document: 2022-12-15.pre
Contact: developers@klaviyo.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

# Common files
require 'klaviyo-api-beta-sdk/api_client'
require 'klaviyo-api-beta-sdk/api_error'
require 'klaviyo-api-beta-sdk/version'
require 'klaviyo-api-beta-sdk/configuration'

# Models
require 'klaviyo-api-beta-sdk/models/audiences_sub_object'
require 'klaviyo-api-beta-sdk/models/campaign_clone_query'
require 'klaviyo-api-beta-sdk/models/campaign_clone_query_as_sub_resource'
require 'klaviyo-api-beta-sdk/models/campaign_clone_query_as_sub_resource_attributes'
require 'klaviyo-api-beta-sdk/models/campaign_create_query'
require 'klaviyo-api-beta-sdk/models/campaign_create_query_as_sub_resource'
require 'klaviyo-api-beta-sdk/models/campaign_create_query_as_sub_resource_attributes'
require 'klaviyo-api-beta-sdk/models/campaign_message_assign_template_query'
require 'klaviyo-api-beta-sdk/models/campaign_message_assign_template_query_as_sub_resource'
require 'klaviyo-api-beta-sdk/models/campaign_message_assign_template_query_as_sub_resource_attributes'
require 'klaviyo-api-beta-sdk/models/campaign_message_partial_update_query'
require 'klaviyo-api-beta-sdk/models/campaign_message_partial_update_query_as_sub_resource'
require 'klaviyo-api-beta-sdk/models/campaign_message_partial_update_query_as_sub_resource_attributes'
require 'klaviyo-api-beta-sdk/models/campaign_partial_update_query'
require 'klaviyo-api-beta-sdk/models/campaign_partial_update_query_as_sub_resource'
require 'klaviyo-api-beta-sdk/models/campaign_partial_update_query_as_sub_resource_attributes'
require 'klaviyo-api-beta-sdk/models/campaign_send_job_create_query'
require 'klaviyo-api-beta-sdk/models/campaign_send_job_create_query_as_sub_resource'
require 'klaviyo-api-beta-sdk/models/campaign_send_job_create_query_as_sub_resource_attributes'
require 'klaviyo-api-beta-sdk/models/campaign_send_job_partial_update_query'
require 'klaviyo-api-beta-sdk/models/campaign_send_job_partial_update_query_as_sub_resource'
require 'klaviyo-api-beta-sdk/models/campaign_send_job_partial_update_query_as_sub_resource_attributes'
require 'klaviyo-api-beta-sdk/models/content_sub_object'
require 'klaviyo-api-beta-sdk/models/data_privacy_create_deletion_job_query'
require 'klaviyo-api-beta-sdk/models/data_privacy_create_deletion_job_query_as_sub_resource'
require 'klaviyo-api-beta-sdk/models/data_privacy_create_deletion_job_query_as_sub_resource_attributes'
require 'klaviyo-api-beta-sdk/models/get_campaigns4_xx_response'
require 'klaviyo-api-beta-sdk/models/get_campaigns4_xx_response_errors_inner'
require 'klaviyo-api-beta-sdk/models/get_campaigns4_xx_response_errors_inner_source'
require 'klaviyo-api-beta-sdk/models/included_profile'
require 'klaviyo-api-beta-sdk/models/included_profile_attributes'
require 'klaviyo-api-beta-sdk/models/included_tags'
require 'klaviyo-api-beta-sdk/models/included_tags_links'
require 'klaviyo-api-beta-sdk/models/profile_location'
require 'klaviyo-api-beta-sdk/models/profile_location_latitude'
require 'klaviyo-api-beta-sdk/models/send_options_sub_object'
require 'klaviyo-api-beta-sdk/models/send_strategy_sub_object'
require 'klaviyo-api-beta-sdk/models/send_time_sub_object'
require 'klaviyo-api-beta-sdk/models/static_schedule_options'
require 'klaviyo-api-beta-sdk/models/tag_create_query'
require 'klaviyo-api-beta-sdk/models/tag_create_query_as_sub_resource'
require 'klaviyo-api-beta-sdk/models/tag_create_query_as_sub_resource_attributes'
require 'klaviyo-api-beta-sdk/models/tag_group_create_query'
require 'klaviyo-api-beta-sdk/models/tag_group_create_query_as_sub_resource'
require 'klaviyo-api-beta-sdk/models/tag_group_create_query_as_sub_resource_attributes'
require 'klaviyo-api-beta-sdk/models/tag_group_update_query'
require 'klaviyo-api-beta-sdk/models/tag_group_update_query_as_sub_resource'
require 'klaviyo-api-beta-sdk/models/tag_group_update_query_as_sub_resource_attributes'
require 'klaviyo-api-beta-sdk/models/tag_segment_op'
require 'klaviyo-api-beta-sdk/models/tag_segment_op_data_inner'
require 'klaviyo-api-beta-sdk/models/tag_update_query'
require 'klaviyo-api-beta-sdk/models/tag_update_query_as_sub_resource'
require 'klaviyo-api-beta-sdk/models/tag_update_query_as_sub_resource_attributes'
require 'klaviyo-api-beta-sdk/models/template_clone_query_as_sub_resource'
require 'klaviyo-api-beta-sdk/models/throttled_schedule_options'
require 'klaviyo-api-beta-sdk/models/tracking_options_sub_object'
require 'klaviyo-api-beta-sdk/models/utm_params_sub_object'
require 'klaviyo-api-beta-sdk/models/v2_template_render_query_as_sub_resource'

# APIs
require 'klaviyo-api-beta-sdk/api/campaigns_api'
require 'klaviyo-api-beta-sdk/api/data_privacy_api'
require 'klaviyo-api-beta-sdk/api/flows_api'
require 'klaviyo-api-beta-sdk/api/lists_api'
require 'klaviyo-api-beta-sdk/api/segments_api'
require 'klaviyo-api-beta-sdk/api/tags_api'

# retry logic
require 'retriable'

module KlaviyoBetaAPI
  @is_initialized = false

  class << self
    # Customize default settings for the SDK using block.
    #   KlaviyoBetaAPI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.

 
    # add retriable config
    # todo: check how slow this is
    Configuration.default.class.module_eval { attr_accessor :max_retries, :max_delay }

    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end

      # create wrapper classes
      if !@is_initialized # run this only once
        self.constants.each do |c|
          if c[-3..-1] == "Api"
            attributes = [:attr1]
            wrapper_class = KlaviyoBetaAPI.const_set(c[0..-4], Struct.new(*attributes))
            original_class = KlaviyoBetaAPI.const_get(c)
            
            # recreate methods
            original_class.public_instance_methods(false).each do |m|
              wrapper_class.class_eval { 
                define_singleton_method m do |*arg| 
                  # max_delay=60, max_retries=3
                  # retry_codes = [429,503,504]
                  # only add retriable if both of these are not set
                  max_retries = Configuration.default.max_retries
                  max_delay = Configuration.default.max_delay

                  if (max_retries != nil && max_delay != nil)
                    Retriable.configure do |c|
                      c.tries = max_retries
                      c.max_elapsed_time = max_delay
                      c.on = {
                        KlaviyoBetaAPI::ApiError => [/429/, /503/, /504/]
                      }
                    end
                    Retriable.retriable do
                      KlaviyoBetaAPI.const_get(c).new.send(m, *arg)
                    end
                  else
                    KlaviyoBetaAPI.const_get(c).new.send(m, *arg)
                  end
                end
              }
            end
          end
        end
        @is_initialized = true
      end
    end
  end
end
